# Netlify Build Configuration
[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist/public"
  
  # Build command - remove package-lock to avoid platform-specific native modules
  command = "rm -f package-lock.json && npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=4096"
  SKIP_PREFLIGHT_CHECK = "true"
  GENERATE_SOURCEMAP = "false"
  # Force npm to install platform-specific native modules
  NPM_CONFIG_TARGET_PLATFORM = "linux"
  NPM_CONFIG_TARGET_ARCH = "x64"
  NPM_CONFIG_CACHE = "/opt/buildhome/.npm"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API proxy (if you need to proxy API calls to an external server)
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend-server.com/api/:splat"
#   status = 200
#   force = true
