providers = ["node"]

[variables]
NODE_ENV = "production"

[phases.setup]
cmd = "echo 'Setup phase - no build tools needed'"

[phases.build]
cmd = "echo 'Using pre-built files - skipping build'"

[phases.start]
cmd = "npm start"

