services:
  - type: web
    name: clean-crm
    env: node
    region: oregon
    buildCommand: |
      echo "🔍 Starting build process..."
      node --version
      npm --version
      pwd
      ls -la
      echo "📦 Installing dependencies..."
      npm ci --legacy-peer-deps --production=false --no-audit --no-fund
      echo "⚡ Building application..."
      npx vite build --mode production
      echo "✅ Build complete!"
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DEMO_MODE
        value: false
      - key: VITE_NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /api/health
