services:
  - type: web
    name: clean-crm
    env: node
    region: oregon
    buildCommand: npm ci --legacy-peer-deps && npx vite build --mode production --base=/ --outDir=dist/public
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DEMO_MODE
        value: false
      - key: VITE_NODE_ENV
        value: production
      - key: DISABLE_YARN
        value: true
    autoDeploy: true
    healthCheckPath: /api/health
