services:
  - type: web
    name: clean-crm
    env: node
    region: oregon
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DEMO_MODE
        value: false
    autoDeploy: true
    healthCheckPath: /api/health
